# Generated by Django 6.0.3 on 2026-03-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fare', models.DecimalField(decimal_places=2, default=5.5, max_digits=8)),
                ('surge_multiplier', models.DecimalField(decimal_places=1, default=1.5, max_digits=4)),
                ('surge_cap', models.DecimalField(decimal_places=1, default=4.0, max_digits=4)),
                ('per_km_rate', models.DecimalField(decimal_places=2, default=12.0, max_digits=6)),
                ('per_min_rate', models.DecimalField(decimal_places=2, default=1.5, max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Configuration',
            },
        ),
        migrations.CreateModel(
            name='HeatmapDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=100)),
                ('predicted_surge', models.DecimalField(decimal_places=1, default=1.0, max_digits=4)),
                ('predicted_at_time', models.CharField(default='18:00', max_length=10)),
                ('reason', models.CharField(default='High volume exit predicted', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurgeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=100)),
                ('multiplier', models.DecimalField(decimal_places=1, default=1.0, max_digits=4)),
                ('requests_per_hour', models.IntegerField(default=0)),
                ('active_drivers', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='ride',
            name='vehicle_class',
            field=models.CharField(choices=[('SUV Elite', 'SUV Elite'), ('Business Sedan', 'Business Sedan'), ('Luxury Auto', 'Luxury Auto')], default='Business Sedan', max_length=50),
        ),
    ]
