# Generated by Django 6.0.3 on 2026-03-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_globalconfiguration_heatmapdemand_surgezone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=100)),
                ('action_type', models.CharField(default='SUPPLY_ALERT', max_length=50)),
                ('admin_user', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
